# Generated by Django 4.2.4 on 2023-09-02 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_project_id_alter_project_status_receipt'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
