# Generated by Django 4.2.4 on 2023-09-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_additional_information_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=8, null=True, unique=True, verbose_name='Project ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
