# Generated by Django 4.2.4 on 2023-09-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_alter_userprofile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Sewing', 'Sewing'), ('Laundry', 'Laundry'), ('Logistics', 'Logistics'), ('Client', 'Client')], max_length=30, null=True),
        ),
    ]
