# Generated by Django 4.2.4 on 2023-09-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('General Manager', 'General Manager'), ('Sewer General', 'Sewer General'), ('Laundry Manager', 'Laundry Manager'), ('Logistics Manager', 'Logistics Manager'), ('Sewer', 'Sewer'), ('Laundry Attendant', 'Laundry Attendant'), ('Logistics Attendant', 'Logistics Attendant'), ('Client', 'Client')], max_length=30, null=True),
        ),
    ]
